version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
    networks:
      - wealthwise-net
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      # This points React app to backend from browser via EC2 public IP
      - REACT_APP_API_URL=http://<EC2_PUBLIC_IP>:8000
    networks:
      - wealthwise-net
    stdin_open: true
    tty: true
    restart: always

networks:
  wealthwise-net:
    driver: bridge
